# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Tables_config = debug
  Datalyser_config = debug

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Tables Datalyser

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Tables:
ifneq (,$(Tables_config))
	@echo "==== Building Tables ($(Tables_config)) ===="
	@${MAKE} --no-print-directory -C . -f Tables.make config=$(Tables_config)
endif

Datalyser:
ifneq (,$(Datalyser_config))
	@echo "==== Building Datalyser ($(Datalyser_config)) ===="
	@${MAKE} --no-print-directory -C . -f Datalyser.make config=$(Datalyser_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Tables.make clean
	@${MAKE} --no-print-directory -C . -f Datalyser.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Tables"
	@echo "   Datalyser"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"